stages:
  - Test
  - Publish

Test:
  stage: Test
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://localhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
  services:
    - name: docker:19.03.12-dind
      alias: docker
  script:
    - docker compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from lippia
  artifacts:
    when: always
    paths:
      - target/reports/

GitHub publish:
  stage: Publish
  image: bitnami/git:2.40.1
  script:
    - git remote add github https://$GITHUB_USER:$GITHUB_TOKEN@github.com/Crowdar/lippia-low-code-sample-project.git
    - git checkout main
    - git push -u github main
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
